from __future__ import annotations


# Route selection happens in the state machine. Speech selection is only a
# string lookup followed by placeholder formatting.
DIRECTIVES: dict[str, str] = {
    "customer_identity.order_status.no_caller_name": "May I have your full name?",
    "customer_identity.ticket_status.no_caller_name": "May I have your full name?",
    "customer_identity.customer_support.no_caller_name": "May I have your full name?",
    "customer_identity.order_status.repeat_caller_name": "I didn't catch your name. Could you say it once more?",
    "customer_identity.ticket_status.repeat_caller_name": "I didn't catch your name. Could you say it once more?",
    "customer_identity.customer_support.repeat_caller_name": "I didn't catch your name. Could you say it once more?",
    "customer_identity.order_status.no_name_match": "I couldn't find an account with that name. Would you like me to set up a callback?",
    "customer_identity.ticket_status.no_name_match": "I couldn't find an account with that name. Would you like me to set up a callback?",
    "customer_identity.customer_support.no_name_match": "I couldn't find an account with that name. Would you like me to set up a callback?",
    "customer_identity.order_status.verify_name": "What are the last four digits of your phone number?",
    "customer_identity.ticket_status.verify_name": "What are the last four digits of your phone number?",
    "customer_identity.customer_support.verify_name": "What are the last four digits of your phone number?",
    "customer_identity.order_status.repeat_caller_phone": "I didn't catch the digits. Please say the last four digits one at a time.",
    "customer_identity.ticket_status.repeat_caller_phone": "I didn't catch the digits. Please say the last four digits one at a time.",
    "customer_identity.customer_support.repeat_caller_phone": "I didn't catch the digits. Please say the last four digits one at a time.",
    "customer_identity.order_status.verification_failed": "I couldn't verify the account with those details. Would you like me to set up a callback?",
    "customer_identity.ticket_status.verification_failed": "I couldn't verify the account with those details. Would you like me to set up a callback?",
    "customer_identity.customer_support.verification_failed": "I couldn't verify the account with those details. Would you like me to set up a callback?",
    "customer_lookup.order_status.success": "Your order {order_id} is {status}.",
    "customer_lookup.ticket_status.success": "Your ticket {case_id} is {status}. Its priority is {priority}.",
    "customer_lookup.order_status.no_order_id": "May I have your order ID?",
    "customer_lookup.ticket_status.no_ticket_id": "May I have your ticket ID?",
    "customer_lookup.order_status.repeat_order_id": "I didn't catch the order ID. Please say the digits one at a time.",
    "customer_lookup.ticket_status.repeat_ticket_id": "I didn't catch the ticket ID. Please say the digits one at a time.",
    "customer_lookup.order_status.not_found": "I couldn't find order {order_id} for this account. Would you like me to set up a callback?",
    "customer_lookup.ticket_status.not_found": "I couldn't find ticket {case_id} for this account. Would you like me to set up a callback?",
    "customer_lookup.order_status.identity_required": "I need to identify the caller before I can access the order.",
    "customer_lookup.ticket_status.identity_required": "I need to identify the caller before I can access the ticket.",
    "customer_lookup.customer_support.callback_required": "I'll arrange a support callback so a person can help you.",
    "support_callback.order_status.no_callback_time": "What day and time would work best for a callback?",
    "support_callback.ticket_status.no_callback_time": "What day and time would work best for a callback?",
    "support_callback.customer_support.no_callback_time": "What day and time would work best for a callback?",
    "support_callback.order_status.repeat_callback_time": "I didn't catch the callback time. Could you say it once more?",
    "support_callback.ticket_status.repeat_callback_time": "I didn't catch the callback time. Could you say it once more?",
    "support_callback.customer_support.repeat_callback_time": "I didn't catch the callback time. Could you say it once more?",
    "support_callback.order_status.scheduled": "Your callback is scheduled for {time}.",
    "support_callback.ticket_status.scheduled": "Your callback is scheduled for {time}.",
    "support_callback.customer_support.scheduled": "Your callback is scheduled for {time}.",
}
